spring.application.name=backend
# Conexión a Neon.tech (PostgreSQL)
spring.datasource.url=postgresql://neondb_owner:npg_62SaWcjnUghz@ep-green-brook-agf8pjwc-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_62SaWcjnUghz

# Configuración de Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
